name: Hent Ukeplaner Automatisk

on:
  schedule:
    # Tirsdag til fredag: Kjører kun kl. 07:00 norsk tid (05:00 UTC)
    - cron: '0 5 * * 2-5'

    # Mandag: Kjører kl. 07:00, 08:00 og 09:00 norsk tid (05:00, 06:00 og 07:00 UTC)
    - cron: '0 5 * * 1'
    - cron: '0 6 * * 1'
    - cron: '0 7 * * 1'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v4

      - name: Sett opp Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Installer pakker
        run: |
          pip install requests beautifulsoup4

      - name: Kjør Python-skriptet
        run: |
          python hent_ukeplaner.py

      - name: Lagre og last opp ukeplaner.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ukeplaner.json
          git status
          git diff --staged --quiet || git commit -m "Automatisk oppdatering av ukeplaner.json"
          git push
